### ISSUE TITLE
Easy: Warn when certificate is out of date [JS]

### ISSUE THREAD

**Issue by solderjs** [Daplie/serve-https#1]
Put some code in here to read its own certificate to know when it expires (and console.warn() that).

~~Or hard-code the date when the new cert is issues.~~

**Comment by coolaj86** [comment]
Use this https://github.com/Daplie/cert-info.js

**Comment by mmlanders23** [comment]
Hey @coolaj86! Do you mind if I take this issue? If not, are there any contribution guidelines I should follow?

It seems the file structure might have changed since the pages you referenced no longer exist. Do you think https://github.com/Daplie/serve-https/blob/master/bin/serve-https.js#L71 would be a good place to add the console.warn() ?

**Comment by coolaj86** [comment]
I'd love it if you'd take it!

It actually needs to handle the cases where an existing certificate is provided, like https://github.com/Daplie/serve-https/blob/master/bin/serve-https.js#L293

The letsencrypt certificates are automatically renewed, so it doesn't need to print a warning in that part.

**Comment by l0n3star** [comment]
@solderjs do you still need help with this?  If so I'd like to take it.

**Comment by solderjs** [comment]
@l0n3star What are you using it for?

Check out https://git.coolaj86.com/coolaj86/greenlock-express.js and https://telebit.cloud

**Comment by l0n3star** [comment]
@solderjs  To be honest I am merely looking to contribute.  I saw the first-timers-only tag so thought I'd take a shot.  I checked out greenlock-express but didn't see any open issues with a first timers tag.  Is there any issue there you think a newbie could tackle?

**Comment by solderjs** [comment]
@l0n3star Depends on just how newbie you are. If you're comfortable making http requests iterating nested loops, and have some degree of familiarity you could help with one of the DNS plugins.

I'm @coolaj86 on Keybase. If you contact me there I'll invite you to a channel with some other devs and there's plenty of little tasks that come up - such as documentation fixes - that you could help with too.

**Comment by l0n3star** [comment]
Yes I think I could help with the DNS plugin.  Happy to help with documentation too.  I'll ping you on keybase.
